// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOMaHN1zpIumwMJ6O12Q_6T_ZD3VwWxAo',
    appId: '1:332103194463:web:1adc6f77666bded92248ea',
    messagingSenderId: '332103194463',
    projectId: 'crud-flutter-9a21f',
    authDomain: 'crud-flutter-9a21f.firebaseapp.com',
    storageBucket: 'crud-flutter-9a21f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkscSMhIQ-EH_IwswrxB5tOUZvCFwbRUc',
    appId: '1:332103194463:android:8e41ec520ce5e1562248ea',
    messagingSenderId: '332103194463',
    projectId: 'crud-flutter-9a21f',
    storageBucket: 'crud-flutter-9a21f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFIfSidxx5fLJVHxxEavsWtckPWU059AI',
    appId: '1:332103194463:ios:3e0b30cb5ec30add2248ea',
    messagingSenderId: '332103194463',
    projectId: 'crud-flutter-9a21f',
    storageBucket: 'crud-flutter-9a21f.appspot.com',
    iosClientId: '332103194463-aadm6q70vqqfeohnhci794tep41cm9am.apps.googleusercontent.com',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFIfSidxx5fLJVHxxEavsWtckPWU059AI',
    appId: '1:332103194463:ios:3e0b30cb5ec30add2248ea',
    messagingSenderId: '332103194463',
    projectId: 'crud-flutter-9a21f',
    storageBucket: 'crud-flutter-9a21f.appspot.com',
    iosClientId: '332103194463-aadm6q70vqqfeohnhci794tep41cm9am.apps.googleusercontent.com',
    iosBundleId: 'com.example.crud',
  );
}
